name: "Publish Vermeer Image(latest)"

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/_publish_image_reusable.yml
    with:
      mode: latest
      component: vermeer
      repository_url: apache/incubator-hugegraph-computer
      branch: master
      build_matrix_json: |
        [
          {
            "module": "vermeer",
            "context": "./vermeer",
            "dockerfile": "./vermeer/Dockerfile",
            "image_repo_latest": "hugegraph/vermeer",
            "image_repo_release": "hugegraph/vermeer",
            "platforms_latest": "linux/amd64,linux/arm64",
            "platforms_release": "linux/amd64,linux/arm64",
            "smoke_test": false
          }
        ]
      enable_hash_gate: true
      last_hash_value: ${{ vars.LAST_VERMEER_HASH }}
      last_hash_name: LAST_VERMEER_HASH
      hash_repo_owner: hugegraph
      hash_repo_name: actions
    secrets: inherit
