name: "Publish hubble image(latest)"

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      mvn_args:
        required: false
        default: ''
        description: 'mvn build args, like "MAVEN_ARGS=-P stage"'

jobs:
  publish:
    uses: ./.github/workflows/_publish_image_reusable.yml
    with:
      mode: latest
      component: hubble
      repository_url: apache/hugegraph-toolchain
      branch: master
      build_matrix_json: |
        [
          {
            "module": "hubble",
            "context": ".",
            "dockerfile": "./hugegraph-hubble/Dockerfile",
            "image_repo_latest": "hugegraph/hubble",
            "image_repo_release": "hugegraph/hubble",
            "platforms_latest": "linux/amd64,linux/arm64",
            "platforms_release": "linux/amd64,linux/arm64",
            "smoke_test": false
          }
        ]
      use_mvn_args: true
      mvn_args: ${{ github.event.inputs.mvn_args || '' }}
      enable_hash_gate: true
      last_hash_value: ${{ vars.LAST_HUBBLE_HASH }}
      last_hash_name: LAST_HUBBLE_HASH
      hash_repo_owner: hugegraph
      hash_repo_name: actions
    secrets: inherit
