name: "Publish AI Image(release)"

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: ''
        description: 'The branch name should be like *-x.x.x, for example release-1.0.0'

jobs:
  publish:
    uses: ./.github/workflows/_publish_image_reusable.yml
    with:
      mode: release
      component: ai
      repository_url: apache/incubator-hugegraph-ai
      branch: ${{ inputs.branch }}
      build_matrix_json: |
        [
          {
            "module": "rag",
            "context": ".",
            "dockerfile": "./docker/Dockerfile.llm",
            "image_repo_latest": "hugegraph/rag",
            "image_repo_release": "hugegraph/rag",
            "platforms_latest": "linux/amd64,linux/arm64",
            "platforms_release": "linux/amd64",
            "smoke_test": false
          },
          {
            "module": "rag-bin",
            "context": ".",
            "dockerfile": "./docker/Dockerfile.nk",
            "image_repo_latest": "hugegraph/rag-bin",
            "image_repo_release": "hugegraph/rag-bin",
            "platforms_latest": "linux/amd64",
            "platforms_release": "linux/amd64",
            "smoke_test": false
          }
        ]
    secrets: inherit
