name: "Publish hubble image(release)"

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: ''
        description: 'The branch name should be like *-x.x.x, for example release-1.0.0'
      mvn_args:
        required: false
        default: ''
        description: 'mvn build args, like "MAVEN_ARGS=-P stage"'

jobs:
  publish:
    uses: ./.github/workflows/_publish_image_reusable.yml
    with:
      mode: release
      component: hubble
      repository_url: apache/hugegraph-toolchain
      branch: ${{ inputs.branch }}
      build_matrix_json: |
        [
          {
            "module": "hubble",
            "context": ".",
            "dockerfile": "./hugegraph-hubble/Dockerfile",
            "image_repo_latest": "hugegraph/hubble",
            "image_repo_release": "hugegraph/hubble",
            "platforms_latest": "linux/amd64,linux/arm64",
            "platforms_release": "linux/amd64,linux/arm64",
            "smoke_test": false
          }
        ]
      use_mvn_args: true
      mvn_args: ${{ inputs.mvn_args }}
    secrets: inherit
