name: "Publish Vermeer Image(release)"

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: ''
        description: 'The branch name should be like *-x.x.x, for example release-1.0.0'

jobs:
  publish:
    uses: ./.github/workflows/_publish_image_reusable.yml
    with:
      mode: release
      component: vermeer
      repository_url: apache/incubator-hugegraph-computer
      branch: ${{ inputs.branch }}
      build_matrix_json: |
        [
          {
            "module": "vermeer",
            "context": "./vermeer",
            "dockerfile": "./vermeer/Dockerfile",
            "image_repo_latest": "hugegraph/vermeer",
            "image_repo_release": "hugegraph/vermeer",
            "platforms_latest": "linux/amd64,linux/arm64",
            "platforms_release": "linux/amd64,linux/arm64",
            "smoke_test": false
          }
        ]
    secrets: inherit
